### PR TITLE
renaming OozieParser class to WorkflowXmlParser fix #263

### LINKED ISSUE #263: Rename OozieParser to WorkflowXmlParser
**Describe the bug**
I am always frustrated when classes have bad names
I think that the `OozieParser` class should be called `WorkflowXmlParser`. This will better describe her roles and allow easier understanding of the code.
When this change is made, this application will not apply.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/177

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by LeonardoFurtado**
### JIRA
- [X] My PR addresses the following [Issue](https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/263)
issue and references it in commit message.

### Tests
- [x] My PR has unit tests testing the functionality (or I explained why it needs no tests)

### Commits
- [X] My commits reference the issue in the message using: Fixes #XXX /Closes #XXX or similar.

I changed the class name, instantiations and changed the corresponding test.

### CODE REVIEW

**Comment by mik-laj** [comment]
Could you also change the name of the `parser.py` file to `workflow_xml_parser.py`?

I check why Travis does not work in this PR.

**Comment by LeonardoFurtado** [comment]
Done @mik-laj

**Comment by mik-laj** [comment]
I crated a custom build on Travis: https://travis-ci.org/GoogleCloudPlatform/oozie-to-airflow
Everything is working properly. When we fix Travis tomorrow, we will include this change to the project.

Do you still want to work on something?
I would like to recommend you some simple issues.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/266
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/264
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/265
What do you think about them?

**Comment by LeonardoFurtado** [comment]
I will try to solve them. I'll be really happy to help.

**Pull request merged**
