### PR TITLE
adding more assertions to testOozieExamples, fixes #264

### LINKED ISSUE #264: TestOozieExamples should contain more assertions
**Is your feature request related to a problem? Please describe.**
One of the classes has tests that do not have enough assertions to prevent full regression.
This test to `TestOozieExamples`.

**Describe the solution you'd like**
I would be happy if the assertions check the existence of `ParsedActionNodes` object in `Workflow` object...and field `downstream_names` and `error_xml` in `ParsedActionNodes` objects.
Currently only the first one is checked.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by LeonardoFurtado**
Make sure you have checked _all_ steps below and that above description is correct.

### JIRA
- [x] My PR addresses the following [Issue](https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/264)
issue and references it in commit message.

### Tests
- [X] My PR has unit tests testing the functionality (or I explained why it needs no tests)

### Commits
- [X] My commits reference the issue in the message using: Fixes #XXX /Closes #XXX or similar.

### CODE REVIEW

**Comment by mik-laj** [comment]
Hi,

Thanks very much for this PR. I started the job on Travis with this change.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/266
When the job is completed, I will merge a change to the project.

I have another task for you. This is a bit harder.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/266
Do you want to take it?

**Comment by LeonardoFurtado** [comment]
Yes I do. If i have any questions about what to do in #266 can I leave a comment on it? I intend to continue contributing whenever possible, over time I will better understand the structure of the project.

**Comment by mik-laj** [comment]
Yes. You can ask questions on the issues.  

I'm also available on Slack - Apache Airflow. https://apache-airflow-slack.herokuapp.com/ I'm Kamil Breguła on this slack, but i prefer discussion over issues.

**Comment by sprzedwojski** [comment]
Hi @LeonardoFurtado! I just wanted to say "welcome" in our small community from my part as another contributor to this project. 👋 Thank you for your work so far, good job! 💪
Like @mik-laj said, if you have any questions - don't hesitate to ask under issues.
I am looking forward to your future PRs! 😃

**Comment by LeonardoFurtado** [comment]
Hi @sprzedwojski ! Thank you for your very friendly welcome. I was looking for some project that I can contribute, I believe it can be a good experience for me as a student. I will start the solution for issue #266 today. Thanks again. <3

**Pull request merged**
