### PR TITLE
Adding transformers to OozieConverter constructor, fix #266

### LINKED ISSUE #266: SubWorkflow is not transformed
**Describe the bug**
SubWorkflow is not transformed by transformers, because OozieConverter in SubworfklowMapper does not receive transformers.

**To Reproduce**
Start the conversation process and look at the diagram.
https://o2a-build-artifacts.storage.googleapis.com/commit-c04952ddc8354bcafa340703b30f7ff33f844f4e/output-dot/subwf/subdag_pig.png

**Expected behavior**
The start and end nodes should disappear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by LeonardoFurtado**
Make sure you have checked _all_ steps below and that above description is correct.

### JIRA
- [x] My PR addresses the following [Issue](https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/XXX)
issue and references it in commit message.

### Tests
- [ ] My PR has unit tests testing the functionality (or I explained why it needs no tests)

### Commits
- [x] My commits reference the issue in the message using: Fixes #XXX /Closes #XXX or similar.

Today I started the changes needed for #266. But I am still confusing about changes requested by @mik-laj  in line 215 of `workflow_xml_parser`. With these changes did the current tests need to be changed? I put `None` as the default value for the `transformers` in the constructors.

### CODE REVIEW

**Comment by mik-laj** [comment]
Current tests do not have to be updated. We have very weak assertions for this class because it has a complex logic.

I have prepared a correction that finishes your work.
```
curl https://termbin.com/l27iz | git am
```

**Comment by LeonardoFurtado** [comment]
Thanks @mik-laj !! Can you check this googlebot notification?

**Comment by mik-laj** [comment]
I do not have permission to influence  on Google Bot.  Can you squash all commits and then execute command `git commit --no-edit --reset-aufhor '?

**Comment by LeonardoFurtado** [comment]
I think everything is ok now.

**Comment by sprzedwojski** [comment]
I think this change would be better off as one of the commits in a wider PR, where changes introduced are actually used somewhere - thus demonstrating the need for this code.
Because right now we are passing a new parameter through the constructor, but it's not being used anywhere - which might be confusing as to why this change is needed.

**Comment by potiuk** [comment]
Looks good. But I want to test it in our build: https://travis-ci.org/GoogleCloudPlatform/oozie-to-airflow/builds/555714343

**Comment by mik-laj** [comment]
@sprzedwojski This is related to this issues: https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/266  This will allow you to get to know the context of change

**Comment by potiuk** [comment]
It looks good @mik-laj  - what do you think ?

**Comment by sprzedwojski** [comment]
@mik-laj Yes, I know. And I think the best approach would be to have this commit be a part of a "SubWorkflow is not transformed" PR, instead of a loose PR. This way we'd see why the changes are needed in one PR.

**Comment by LeonardoFurtado** [comment]
Thank you all. I'll try to solve #265  as soon as possible.

**Pull request merged**
