### PR TITLE
Remove no-name-in-module from pylintrc

### LINKED ISSUE #241: Pylint  no-name-in-module error disabled
**Describe the bug**
We had to disable pylint no-name-in-module check because it was mysteriously failing. We need to investigate and fix it and re-enable the check.

**To Reproduce**

1. remove  no-name-in-module from pylintrc
2. run `pre-commit run pylint --all-files`
3. observe errors produced by pylint

**Expected behavior**
Pylint should produce no errors with no-name-in-module enabled.

### PR DESCRIPTION
**Pull request by nuclearpinguin**
Fixes #241 

### JIRA
- [ ] My PR addresses the following [Issue](https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/241)
issue and references it in commit message.

### Tests
- [ ] My PR has unit tests testing the functionality (or I explained why it needs no tests)

### Commits
- [ ] My commits reference the issue in the message using: Fixes #XXX /Closes #XXX or similar.

### Documentation
- [ ] My PR adds documentation that describes how to use it (or I explained why it needs no docs)

### CODE REVIEW

**Comment by sprzedwojski** [comment]
From #241:
> Expected behavior
> Pylint should produce no errors with no-name-in-module enabled.

Shouldn't we strive to have the `no-name-in-module` present and enabled and the pylint passing, rather than removing the check?

**Comment by nuclearpinguin** [comment]
This PR enables `no-name-in-module` check. Green travis confirms that #241 error does not occur.

**Comment by potiuk** [comment]
> From #241:
> 
> > Expected behavior
> > Pylint should produce no errors with no-name-in-module enabled.
> 
> Shouldn't we strive to have the `no-name-in-module` present and enabled and the pylint passing, rather than removing the check?

This is an "exclusion" list - to "inclusion" - so we are bringing back the check that failed before and we did not know what to do.

**Comment by sprzedwojski** [comment]
I've seen that you have the `Merge branch 'master' into pylint-fix` commit again.
Do you use the GitHub's button which says something like "merge with master" here?

I'd recommend manually rebasing your branch on top of master locally and then pushing it with `--force`. This way this merge commit will not appear.

**Comment by potiuk** [comment]
Agree with @sprzedwojski . As of recently I am also using `--force-with-lease` which protects you agains accidental overrides if someone pushes at the same time as you to the same branch (but this is really not needed in this case as only you work on this branch).

Also side comment - the merge commits will disappear after "squash and merge" but it's much nicer to review the code with push --force indeed.

**Pull request merged**
